# Generated by Django 4.2.6 on 2023-11-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_remove_profile_location_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
