# Generated by Django 4.2.6 on 2023-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(null=True),
        ),
    ]
