# Generated by Django 4.2.6 on 2023-11-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_listing_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
