# Generated by Django 4.2.6 on 2023-11-08 16:06

import backend_project.backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=backend_project.backend_app.models.upload_to),
        ),
    ]
