# Generated by Django 4.2.6 on 2023-11-08 18:03

import backend_project.backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(blank=True, height_field='250', null=True, upload_to=backend_project.backend_app.models.upload_to, width_field='250'),
        ),
    ]
