# Generated by Django 4.2.6 on 2023-11-09 16:26

import backend_project.backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=backend_project.backend_app.models.upload_to),
        ),
    ]
