# Generated by Django 4.2.6 on 2023-11-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
