# Generated by Django 4.2.6 on 2023-11-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
