# Generated by Django 4.2.6 on 2023-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_cart_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
