# Generated by Django 4.2.6 on 2023-11-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_alter_cart_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
