# Generated by Django 4.2.6 on 2026-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('great', 'Great'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=10, null=True),
        ),
    ]
